{ pkgs, ... }:

{
  home.packages = [
    # You can find these packages with `nix-env -f '<nixpkgs>' -qaP -A python3Packages`
    # Note the headings and descriptions were (mostly) generated by ChatGPT
    (pkgs.python3.withPackages (p: with p; [
      # Deep Learning Frameworks
      torch               # PyTorch framework for deep learning
      torchvision         # Vision utilities for PyTorch
      open-clip-torch     # CLIP (Contrastive Language-Image Pretraining) model for PyTorch
      tensorflow          # TensorFlow, a machine learning framework
      keras               # High-level neural networks API, often used with TensorFlow

      # Monitoring & Profiling
      tensorboard         # TensorFlow's visualization toolkit
      torch-tb-profiler   # PyTorch profiler for TensorBoard integration
      wandb               # Weights & Biases for experiment tracking

      # Optimization & Reinforcement Learning
      stable-baselines3   # Reinforcement learning library based on PyTorch
      gymnasium           # Gymnasium, RL environment toolkit
      gymnasium[box2d]    # Gymnasium environment for 2D physics simulations
      mujoco              # Physics engine for robotics and reinforcement learning
      
      # Data Science & Scientific Computing
      numpy               # Fundamental package for scientific computing with Python
      scipy               # Scientific computing library for Python
      pandas              # Data analysis and manipulation library
      matplotlib          # Plotting library for creating static, animated, and interactive visualizations
      plotly              # Interactive graphing library
      opencv-python       # Computer vision library
      imageio             # Reading and writing image data
      
      # Game Development & Simulation
      pygame              # Game development library for creating games
      pyglet              # Library for game development, windowing, and multimedia
      pyvista             # 3D plotting and mesh analysis library
      
      # Automation & GUI
      pyautogui           # Automation library for GUI control
      pynput              # Library to monitor and control input devices (keyboard/mouse)
      pure-python-adb     # Python library for controlling Android devices via ADB
      discordpy           # Library for creating Discord bots
      
      # Simulation & Control
      brian2              # Simulator for spiking neural networks
      
      # Exploitation/Hacking
      pwntools            # CTF framework and exploit development library

      # Miscellaneous
      python-dotenv       # Read environment variables from .env file
    ]))
  ];
}
